// Printing without a second window.
//
// The card used to be written into a popup (`window.open("", "_blank")`). The
// hub's app frame does not grant popups, so the card is now built into a
// container in THIS document that is `display: none` on screen at all times and
// shown only by `@media print` while <html> carries PRINTING_CLASS (the rules
// live in index.html). Nothing here imports the SDK or touches a global, so the
// markup and the lifecycle are both testable from Node.

import { SEV_LABEL, SEV_CLASS } from "./logic.js";

export const PRINT_ROOT_CLASS = "print-root";
export const PRINTING_CLASS = "printing";

/**
 * The printable card, as markup for the print container.
 *
 * `esc` is the SDK's HTML escape and `glyph` its icon helper; both are passed
 * in because this module must stay importable without the hub. EVERY stored
 * value goes through `esc` — these are free-text fields a member typed.
 * This is the complete list of what reaches paper; add nothing to it lightly.
 */
export function printCardMarkup({ member, allergies, medications, contacts, printDate }, { esc, glyph }) {
  const e = (s) => esc(s ?? "");
  const al = allergies ?? [];
  const ml = medications ?? [];
  const cl = contacts ?? [];

  const allergyBlocks = al.map(a => `
    <div class="entry">
      <div class="entry-name">${e(a.name)} <span class="sev-tag ${SEV_CLASS[a.severity] ?? "sev-moderate"}">${SEV_LABEL[a.severity] ?? "Moderate"}</span></div>
      ${a.triggers       ? `<div class="entry-line"><strong>Triggers:</strong> ${e(a.triggers)}</div>` : ""}
      ${a.symptoms       ? `<div class="entry-line"><strong>Reaction signs:</strong> ${e(a.symptoms)}</div>` : ""}
      ${a.response_steps ? `<div class="entry-line"><strong>What to do:</strong><div class="steps">${e(a.response_steps).replace(/\n/g, "<br>")}</div></div>` : ""}
    </div>`).join("");

  const medBlocks = ml.map(m => `
    <div class="entry">
      <div class="entry-name">${e(m.name)} ${m.dose ? `<span class="dose-tag">${e(m.dose)}</span>` : ""}</div>
      ${m.when_to_give ? `<div class="entry-line"><strong>When:</strong> ${e(m.when_to_give)}</div>` : ""}
      ${m.location     ? `<div class="entry-line"><strong>Location:</strong> ${e(m.location)}</div>` : ""}
      ${m.notes        ? `<div class="entry-line note">${e(m.notes)}</div>` : ""}
    </div>`).join("");

  const contactBlocks = cl.map((c, i) => `
    <div class="contact-row">
      <div class="contact-num">${i + 1}</div>
      <div>
        <div class="entry-name">${e(c.name)} ${c.relationship ? `<span class="rel-tag">${e(c.relationship)}</span>` : ""}</div>
        ${c.phone ? `<div class="phone">${e(c.phone)}</div>` : ""}
      </div>
    </div>`).join("");

  return `
<div class="card-title">Emergency Health Card — ${e(member?.name)}</div>
<div class="card-meta">Printed ${e(printDate)} · Keep with the child at all times</div>

${al.length > 0 ? `<div class="section"><div class="section-title">${glyph("warning")} Allergies</div>${allergyBlocks}</div>` : ""}
${ml.length > 0 ? `<div class="section"><div class="section-title">Emergency Medications</div>${medBlocks}</div>` : ""}
${cl.length > 0 ? `<div class="section"><div class="section-title">Emergency Contacts</div>${contactBlocks}</div>` : ""}
${al.length === 0 && ml.length === 0 && cl.length === 0 ? "<p>No health information on file for this person.</p>" : ""}

<div class="footer">Verify all information before distributing. Generated by your family health records.</div>`;
}

// The teardown of the print that is still open, if any.
let endCurrentPrint = null;

/**
 * Print `markup` from this document: mount it in a hidden container, flag
 * <html>, call `win.print()`, and take all of it away again afterwards.
 *
 * Teardown runs once, on whichever comes first:
 *   - `afterprint`;
 *   - the `print` media query going false (browsers that skip `afterprint`);
 *   - `pagehide`;
 *   - the first pointer or key event after `print()` has returned. The print
 *     dialog is modal, so input reaching the page means it is gone. This is
 *     the fallback for a browser that fires neither of the first two, and it
 *     is armed only after `print()` returns so the click that started the
 *     print cannot end it.
 * There is deliberately no timer: where `print()` does not block, a timer
 * would empty the page out from under an open print preview.
 *
 * Returns the teardown (idempotent), or null when printing is unavailable.
 */
export function printInPlace(win, markup, { title } = {}) {
  if (endCurrentPrint) endCurrentPrint();
  const doc = win?.document;
  if (!doc?.body || typeof win.print !== "function") return null;

  const root = doc.createElement("div");
  root.className = PRINT_ROOT_CLASS;
  root.innerHTML = markup;
  doc.body.appendChild(root);

  const previousTitle = doc.title;
  if (title) doc.title = title; // names the print job / the saved PDF
  doc.documentElement.classList.add(PRINTING_CLASS);

  const media = typeof win.matchMedia === "function" ? win.matchMedia("print") : null;
  const INPUT_EVENTS = ["pointerdown", "keydown"];
  let done = false;
  let armTimer = null;

  function onMedia(event) { if (!event.matches) finish(); }
  function finish() {
    if (done) return;
    done = true;
    root.remove();
    doc.documentElement.classList.remove(PRINTING_CLASS);
    if (title) doc.title = previousTitle;
    win.removeEventListener("afterprint", finish);
    win.removeEventListener("pagehide", finish);
    for (const name of INPUT_EVENTS) win.removeEventListener(name, finish, true);
    media?.removeEventListener?.("change", onMedia);
    if (armTimer !== null) win.clearTimeout(armTimer);
    if (endCurrentPrint === finish) endCurrentPrint = null;
  }
  endCurrentPrint = finish;

  win.addEventListener("afterprint", finish);
  win.addEventListener("pagehide", finish);
  media?.addEventListener?.("change", onMedia);

  try {
    win.print();
  } catch {
    finish();
    return null;
  }
  if (!done) {
    armTimer = win.setTimeout(() => {
      armTimer = null;
      if (done) return;
      for (const name of INPUT_EVENTS) win.addEventListener(name, finish, true);
    }, 0);
  }
  return finish;
}
