import { readFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
import { describe, it, expect } from "vitest";
import { printCardMarkup, printInPlace, PRINT_ROOT_CLASS, PRINTING_CLASS } from "../src/print.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const html = readFileSync(join(__dirname, "../src/index.html"), "utf-8");

// The SDK's `esc`, restated: the SDK is served by the hub and is not in this repo.
const esc = (s) => String(s)
  .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
  .replace(/"/g, "&quot;").replace(/'/g, "&#39;");
const glyph = (name) => `[glyph:${name}]`;
const helpers = { esc, glyph };

const XSS = `<script>alert("x")</script>`;
const XSS_ESCAPED = "&lt;script&gt;alert(&quot;x&quot;)&lt;/script&gt;";

const full = {
  member: { id: "m1", name: "Robin" },
  allergies: [{ name: "Peanuts", severity: "anaphylactic", triggers: "Any nut", symptoms: "Hives", response_steps: "Use pen\nCall 911" }],
  medications: [{ name: "EpiPen", dose: "0.15mg", when_to_give: "At first sign", location: "Front pocket", notes: "Expires May" }],
  contacts: [
    { name: "Sam Parent", relationship: "Dad", phone: "555-0100" },
    { name: "Dr Lee", relationship: "", phone: "" },
  ],
  printDate: "October 7, 2026",
};

describe("printCardMarkup", () => {
  it("prints every field of every section", () => {
    const out = printCardMarkup(full, helpers);
    for (const text of [
      "Emergency Health Card — Robin",
      "Printed October 7, 2026 · Keep with the child at all times",
      "[glyph:warning] Allergies", "Peanuts", "Anaphylactic", "sev-anaphylactic",
      "<strong>Triggers:</strong> Any nut",
      "<strong>Reaction signs:</strong> Hives",
      "<strong>What to do:</strong>", "Use pen<br>Call 911",
      "Emergency Medications", "EpiPen", "0.15mg",
      "<strong>When:</strong> At first sign",
      "<strong>Location:</strong> Front pocket",
      "Expires May",
      "Emergency Contacts", "Sam Parent", "Dad", "555-0100", "Dr Lee",
      "Verify all information before distributing. Generated by your family health records.",
    ]) expect(out, text).toContain(text);
    // Contacts are numbered in order.
    expect(out).toMatch(/contact-num">1<[\s\S]*Sam Parent[\s\S]*contact-num">2<[\s\S]*Dr Lee/);
    expect(out).not.toContain("No health information on file");
  });

  it("escapes every interpolated value", () => {
    const out = printCardMarkup({
      member: { name: XSS },
      allergies: [{ name: XSS, severity: "mild", triggers: XSS, symptoms: XSS, response_steps: XSS }],
      medications: [{ name: XSS, dose: XSS, when_to_give: XSS, location: XSS, notes: XSS }],
      contacts: [{ name: XSS, relationship: XSS, phone: XSS }],
      printDate: XSS,
    }, helpers);
    expect(out).not.toContain("<script");
    // 1 member + 4 allergy + 5 medication + 3 contact + 1 date
    expect(out.split(XSS_ESCAPED).length - 1).toBe(14);
  });

  it("escapes quotes, so a value cannot close an attribute", () => {
    const out = printCardMarkup({ ...full, member: { name: `O'Brien "Bo"` } }, helpers);
    expect(out).toContain("O&#39;Brien &quot;Bo&quot;");
  });

  it("an unknown severity cannot inject a class or label", () => {
    const out = printCardMarkup({ ...full, allergies: [{ name: "Dust", severity: `x" onload="y` }] }, helpers);
    expect(out).toContain(`<span class="sev-tag sev-moderate">Moderate</span>`);
    expect(out).not.toContain("onload");
  });

  it("omits empty sections and optional lines, and prints no literal null/undefined", () => {
    const out = printCardMarkup({
      member: { name: null },
      allergies: [{ name: "Dust", severity: "mild" }],
      medications: [],
      contacts: [],
      printDate: "October 7, 2026",
    }, helpers);
    expect(out).toContain("Dust");
    expect(out).not.toContain("Triggers:");
    expect(out).not.toContain("Emergency Medications");
    expect(out).not.toContain("Emergency Contacts");
    expect(out).not.toMatch(/\bnull\b|\bundefined\b/);
  });

  it("says so when there is nothing on file", () => {
    const out = printCardMarkup({ member: { name: "Robin" }, allergies: [], medications: [], contacts: [], printDate: "x" }, helpers);
    expect(out).toContain("<p>No health information on file for this person.</p>");
    expect(out).not.toContain('class="section"');
  });

  it("carries no script, handler, or control of its own", () => {
    const out = printCardMarkup(full, helpers);
    expect(out).not.toMatch(/<script|<button|\son\w+=/i);
  });
});

// ── printInPlace ────────────────────────────────────────────────────────────
// A window with just the surface printInPlace uses. `onPrint` stands in for the
// browser's print dialog; timers are collected so the test decides when they run.
function fakeWindow({ onPrint = () => {}, withMedia = true } = {}) {
  const listeners = new Map();
  const mediaListeners = new Set();
  const timers = [];
  const children = [];
  const classes = new Set();
  const win = {
    printCalls: 0,
    timers,
    children,
    classes,
    document: {
      title: "App",
      body: { appendChild(node) { children.push(node); node.parent = children; } },
      documentElement: { classList: { add: (c) => classes.add(c), remove: (c) => classes.delete(c) } },
      createElement: () => ({
        className: "", innerHTML: "", parent: null,
        remove() { const i = children.indexOf(this); if (i >= 0) children.splice(i, 1); },
      }),
    },
    addEventListener(name, fn) { if (!listeners.has(name)) listeners.set(name, new Set()); listeners.get(name).add(fn); },
    removeEventListener(name, fn) { listeners.get(name)?.delete(fn); },
    fire(name) { for (const fn of [...(listeners.get(name) ?? [])]) fn({ type: name }); },
    listenerCount() { let n = mediaListeners.size; for (const set of listeners.values()) n += set.size; return n; },
    setTimeout(fn) { timers.push(fn); return timers.length; },
    clearTimeout(id) { if (id) timers[id - 1] = null; },
    runTimers() { for (const fn of timers.splice(0)) fn?.(); },
    fireMedia(matches) { for (const fn of [...mediaListeners]) fn({ matches }); },
    print() { win.printCalls++; onPrint(win); },
  };
  if (withMedia) {
    win.matchMedia = () => ({
      addEventListener: (_name, fn) => mediaListeners.add(fn),
      removeEventListener: (_name, fn) => mediaListeners.delete(fn),
    });
  }
  return win;
}

function expectClean(win) {
  expect(win.children).toEqual([]);
  expect(win.classes.has(PRINTING_CLASS)).toBe(false);
  expect(win.document.title).toBe("App");
  expect(win.listenerCount()).toBe(0);
}

describe("printInPlace", () => {
  it("mounts the markup in a print root, flags <html>, and prints this window", () => {
    let seen = null;
    const win = fakeWindow({
      onPrint: (w) => { seen = { root: w.children[0], printing: w.classes.has(PRINTING_CLASS), title: w.document.title }; },
    });
    printInPlace(win, "<p>card</p>", { title: "Job" });
    expect(win.printCalls).toBe(1);
    expect(seen.root.className).toBe(PRINT_ROOT_CLASS);
    expect(seen.root.innerHTML).toBe("<p>card</p>");
    expect(seen.printing).toBe(true);
    expect(seen.title).toBe("Job");
    win.fire("afterprint");
  });

  it("leaves nothing behind when afterprint fires during print() (blocking dialog)", () => {
    const win = fakeWindow({ onPrint: (w) => w.fire("afterprint") });
    printInPlace(win, "<p>card</p>", { title: "Job" });
    win.runTimers();
    expectClean(win);
  });

  it("leaves nothing behind when afterprint fires later (non-blocking dialog)", () => {
    const win = fakeWindow();
    printInPlace(win, "<p>card</p>", { title: "Job" });
    win.runTimers();
    expect(win.children.length).toBe(1); // still there for the open dialog
    win.fire("afterprint");
    expectClean(win);
  });

  it("cleans up when the print media query goes false and afterprint never fires", () => {
    const win = fakeWindow();
    printInPlace(win, "<p>card</p>", { title: "Job" });
    win.fireMedia(true);
    expect(win.children.length).toBe(1);
    win.fireMedia(false);
    expectClean(win);
  });

  it("falls back to the first input after print() returned when no print event ever fires", () => {
    const win = fakeWindow({ withMedia: false });
    printInPlace(win, "<p>card</p>", { title: "Job" });
    // The click that started the print is still being dispatched: it must not end it.
    win.fire("pointerdown");
    expect(win.children.length).toBe(1);
    win.runTimers();
    win.fire("pointerdown");
    expectClean(win);
  });

  it("cleans up on pagehide and on a keypress", () => {
    const a = fakeWindow();
    printInPlace(a, "<p>card</p>", { title: "Job" });
    a.fire("pagehide");
    expectClean(a);

    const b = fakeWindow();
    printInPlace(b, "<p>card</p>", { title: "Job" });
    b.runTimers();
    b.fire("keydown");
    expectClean(b);
  });

  it("a second print replaces the first rather than stacking two cards", () => {
    const win = fakeWindow();
    printInPlace(win, "<p>one</p>", { title: "Job" });
    printInPlace(win, "<p>two</p>", { title: "Job" });
    expect(win.children.map(c => c.innerHTML)).toEqual(["<p>two</p>"]);
    win.fire("afterprint");
    expectClean(win);
  });

  it("cleans up and returns null when print() throws", () => {
    const win = fakeWindow({ onPrint: () => { throw new Error("blocked"); } });
    expect(printInPlace(win, "<p>card</p>", { title: "Job" })).toBe(null);
    expectClean(win);
  });

  it("the returned teardown is idempotent", () => {
    const win = fakeWindow();
    const end = printInPlace(win, "<p>card</p>", { title: "Job" });
    end(); end();
    win.fire("afterprint");
    expectClean(win);
  });
});

// ── The page wiring ─────────────────────────────────────────────────────────
describe("index.html prints in place", () => {
  it("opens no window and writes no second document", () => {
    expect(html).not.toMatch(/window\.open\s*\(/);
    expect(html).not.toMatch(/document\.write\s*\(/);
  });

  it("keeps the print root off screen and shows only it in print", () => {
    const css = html.replace(/\s+/g, " ");
    expect(css).toMatch(/\.print-root \{ display: none;/);
    const printBlock = css.match(/@media print \{(.*?)\} \}/)?.[1] ?? "";
    expect(printBlock).toContain("html.printing body > *:not(.print-root) { display: none !important; }");
    expect(printBlock).toContain("html.printing .print-root { display: block;");
    // The root itself is given a visible display nowhere outside print media.
    expect(css.split("@media print")[0]).not.toMatch(/\.print-root \{[^}]*display: (?!none)/);
  });
});
